config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users, controllers: { 
    sessions: "users/sessions" 
  }

  resources :users do 
    resources :readings 
    resources :systolic_ranges
  end

   root 'readings#index'

end

app/models/reading.rb
class Reading < ActiveRecord::Base
	belongs_to :user
end

app/controllers/readings_controller.rb
require 'twilio-ruby'
class ReadingsController < ApplicationController
  before_action :set_reading, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  # GET /readings
  # GET /readings.json
  def index
    @user = current_user
    @systolic_range = SystolicRange.new
    @readings = Reading.all
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit
    
  end

  # POST /readings
  # POST /readings.json
  def create
    @user = current_user
    @reading = Reading.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to user_readings_path, notice: 'Reading was successfully created.' }
        format.json { render :show, status: :created, location: @reading }
          if @reading.systolic > current_user.systolic_range.high || @reading.diastolic < current_user.systolic_range.low
            # Get your Account Sid and Auth Token from twilio.com/user/account
            account_sid = 'AC63de569ccbfd715bed71f1bd6d884215'
            auth_token = '447c2138b017c4bf199553496fab3554'
            @client = Twilio::REST::Client.new account_sid, auth_token
   
            message = @client.account.messages.create(:body => "#{current_user.firstname} #{current_user.lastname}'s blood pressure is outside of normal range",
                :to => current_user.guardian_phone_number, 
                :from => current_user.phone_number)
            puts message.to
          end
      else
        format.html { render :new }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to user_readings_path, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
       if @reading.systolic > current_user.systolic_range.high || @reading.diastolic < current_user.systolic_range.low
            # Get your Account Sid and Auth Token from twilio.com/user/account
            account_sid = 'AC63de569ccbfd715bed71f1bd6d884215'
            auth_token = '447c2138b017c4bf199553496fab3554'
            @client = Twilio::REST::Client.new account_sid, auth_token
   
            message = @client.account.messages.create(:body => "#{current_user.firstname} #{current_user.lastname}'s blood pressure is outside of normal range",
                :to => current_user.guardian_phone_number, 
                :from => current_user.phone_number)
            puts message.to
          end
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy

    @reading.destroy
    respond_to do |format|
      format.html { redirect_to user_readings_path(current_user), notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @user = current_user
      @reading = Reading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reading_params
      params.require(:reading).permit(:systolic, :diastolic, :heart_rate, :time)
    end
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/readings/_form.html.erb
<%= form_for [current_user, @reading] do |f| %>
  <% if @reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :systolic %><br>
    <%= f.number_field :systolic %>
  </div>
  <div class="field">
    <%= f.label :diastolic %><br>
    <%= f.number_field :diastolic %>
  </div>
  <div class="field">
    <%= f.label :heart_rate %><br>
    <%= f.number_field :heart_rate %>
  </div>
  <div class="field">
    <%= f.label :time %> <br> 
    <%= f.datetime_local_field :time %> 
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/_systolic_form.html.erb
<%= form_for [@user, @systolic_range] do |f| %>
  <% if @systolic_range.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@systolic_range.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
      <% @systolic_range.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <th>
      <tr>
        <td><%= f.label :low %></td>
        <td><%= f.label :medium %></td>
        <td><%= f.label :high %></td>
      </tr>
    </th>
      <tr>
        <td><%= f.number_field :low %></td>
        <td><%= f.number_field :medium %></td>
        <td><%= f.number_field :high %></td>
        <td><%= f.hidden_field :user_id, value: current_user.id %> </td>
      </tr>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing Reading</h1>

<%= render 'form' %>

<%= link_to 'Show', user_reading_path %> |
<%= link_to 'Back', user_readings_path %>

app/views/readings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Hi, <%= @user.firstname %> </h1>

<h2>Please Enter Your Systolic Range</h2>

  <% if @user.systolic_range %> 
    <table>
      <th>
        <tr>
          <td>Low </td>
          <td>Medium </td>
          <td>High </td>
        </tr>
      </th>
        <tr>
          <td><%= @user.systolic_range.low %></td>
          <td><%= @user.systolic_range.medium %></td>
          <td><%= @user.systolic_range.high %></td>
        </tr>
        <tr>
          <td></td>
        </tr>
        <tr>
          <td><%= link_to 'Edit', edit_user_systolic_range_path(@user, @user.systolic_range) %></td>
        </tr>
    </table>
  <% else %>
    <%= render 'systolic_form' %>
  <% end %>  

<h2>Log Your Blood Pressure Readings</h2>

<table>
  <thead>
    <tr> 
      <th>Systolic</th>
      <th>Diastolic</th>
      <th>Heart rate</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @readings.each do |reading| %>
      <tr>
        <td><%= reading.systolic %></td>
        <td><%= reading.diastolic %></td>
        <td><%= reading.heart_rate %></td>
        <td><%= reading.time %></td>
        <td><%= link_to 'Show', user_reading_path(current_user, reading)%></td>
        <td><%= link_to 'Edit', edit_user_reading_path(current_user, reading) %></td>
        <td><%= link_to 'Destroy', user_reading_path(current_user, reading), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reading', new_user_reading_path(current_user) %>

app/views/readings/new.html.erb
<h1>New Reading</h1>

<%= render 'form' %>

<%= link_to 'Back', user_readings_path(current_user) %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Systolic:</strong>
  <%= @reading.systolic %>
</p>

<p>
  <strong>Diastolic:</strong>
  <%= @reading.diastolic %>
</p>

<p>
  <strong>Heart rate:</strong>
  <%= @reading.heart_rate %>
</p>

<%= link_to 'Edit', edit_user_reading_path %> |
<%= link_to 'Back', user_readings_path %>